FROM node:20-alpine AS builder

WORKDIR /frontend


COPY package*.json ./
RUN npm ci --only=production


COPY . .
RUN npm run build

FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /frontend/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]