from typing import Protocol

class TableReportProtocol(Protocol):
    def get_rows_number(self, table_title: str) -> int:
        ...
    def get_cheked_number(self, table_title: str) -> int:
        ...
    def get_success_number(self, table_title: str) -> int:
        ...
    def get_remarks_number(self, table_title: str) -> int:
        ...
    def get_elem_remarks_td_number(self, table_title: str) -> int:
        ...
    def get_remarks_td_number(self, table_title: str) -> int:
        ...
    def get_cheked_td_number(self, table_title: str) -> int:
        ...